import HTMLTemplateElement from '../nodes/elements/template/HTMLTemplateElement';
import HTMLFormElement from '../nodes/elements/form/HTMLFormElement';
import HTMLElement from '../nodes/basic/html-element/HTMLElement';
import HTMLInputElement from '../nodes/elements/input/HTMLInputElement';
import HTMLTextAreaElement from '../nodes/elements/text-area/HTMLTextAreaElement';
import SVGSVGElement from '../nodes/elements/svg/SVGSVGElement';
import SVGElement from '../nodes/elements/svg/SVGElement';

export default {
	HTMLTemplateElement: HTMLTemplateElement,
	HTMLFormElement: HTMLFormElement,
	HTMLInputElement: HTMLInputElement,
	HTMLTextAreaElement: HTMLTextAreaElement,
	HTMLElement: HTMLElement,
	HTMLHeadElement: HTMLElement,
	HTMLTitleElement: HTMLElement,
	HTMLBaseElement: HTMLElement,
	HTMLLinkElement: HTMLElement,
	HTMLMetaElement: HTMLElement,
	HTMLStyleElement: HTMLElement,
	HTMLBodyElement: HTMLElement,
	HTMLHeadingElement: HTMLElement,
	HTMLParagraphElement: HTMLElement,
	HTMLHRElement: HTMLElement,
	HTMLPreElement: HTMLElement,
	HTMLUListElement: HTMLElement,
	HTMLOListElement: HTMLElement,
	HTMLLIElement: HTMLElement,
	HTMLMenuElement: HTMLElement,
	HTMLDListElement: HTMLElement,
	HTMLDivElement: HTMLElement,
	HTMLAnchorElement: HTMLElement,
	HTMLAreaElement: HTMLElement,
	HTMLBRElement: HTMLElement,
	HTMLButtonElement: HTMLElement,
	HTMLCanvasElement: HTMLElement,
	HTMLDataElement: HTMLElement,
	HTMLDataListElement: HTMLElement,
	HTMLDetailsElement: HTMLElement,
	HTMLDialogElement: HTMLElement,
	HTMLDirectoryElement: HTMLElement,
	HTMLFieldSetElement: HTMLElement,
	HTMLFontElement: HTMLElement,
	HTMLHtmlElement: HTMLElement,
	HTMLImageElement: HTMLElement,
	HTMLLabelElement: HTMLElement,
	HTMLLegendElement: HTMLElement,
	HTMLMapElement: HTMLElement,
	HTMLMarqueeElement: HTMLElement,
	HTMLMediaElement: HTMLElement,
	HTMLMeterElement: HTMLElement,
	HTMLModElement: HTMLElement,
	HTMLOptGroupElement: HTMLElement,
	HTMLOptionElement: HTMLElement,
	HTMLOutputElement: HTMLElement,
	HTMLPictureElement: HTMLElement,
	HTMLProgressElement: HTMLElement,
	HTMLQuoteElement: HTMLElement,
	HTMLScriptElement: HTMLElement,
	HTMLSelectElement: HTMLElement,
	HTMLSlotElement: HTMLElement,
	HTMLSourceElement: HTMLElement,
	HTMLSpanElement: HTMLElement,
	HTMLTableCaptionElement: HTMLElement,
	HTMLTableCellElement: HTMLElement,
	HTMLTableColElement: HTMLElement,
	HTMLTableElement: HTMLElement,
	HTMLTimeElement: HTMLElement,
	HTMLTableRowElement: HTMLElement,
	HTMLTableSectionElement: HTMLElement,
	HTMLUnknownElement: HTMLElement,
	HTMLFrameElement: HTMLElement,
	HTMLFrameSetElement: HTMLElement,
	HTMLIFrameElement: HTMLElement,
	HTMLEmbedElement: HTMLElement,
	HTMLObjectElement: HTMLElement,
	HTMLParamElement: HTMLElement,
	HTMLVideoElement: HTMLElement,
	HTMLAudioElement: HTMLElement,
	HTMLTrackElement: HTMLElement,
	SVGSVGElement: SVGSVGElement,
	SVGElement: SVGElement
};
