import { Script } from 'vm';

export default new Script(`
this.ArrayBuffer = ArrayBuffer;
this.Boolean = Boolean;
this.DataView = DataView;
this.Date = Date;
this.Error = Error;
this.EvalError = EvalError;
this.Float32Array = Float32Array;
this.Float64Array = Float64Array;
this.GLOBAL = typeof GLOBAL === 'undefined' ? undefined : GLOBAL;
this.Infinity = Infinity;
this.Int16Array = Int16Array;
this.Int32Array = Int32Array;
this.Int8Array = Int8Array;
this.Intl = Intl;
this.JSON = JSON;
this.Map = Map;
this.Math = Math;
this.NaN = NaN;
this.Number = Number;
this.Promise = Promise;
this.RangeError = RangeError;
this.ReferenceError = ReferenceError;
this.RegExp = RegExp;
this.Reflect = Reflect;
this.Set = Set;
this.Symbol = Symbol;
this.SyntaxError = SyntaxError;
this.String = String;
this.TypeError = TypeError;
this.URIError = URIError;
this.Uint16Array = Uint16Array;
this.Uint32Array = Uint32Array;
this.Uint8Array = Uint8Array;
this.Uint8ClampedArray = Uint8ClampedArray;
this.WeakMap = WeakMap;
this.WeakSet = WeakSet;
this.decodeURI = decodeURI;
this.decodeURIComponent = decodeURIComponent;
this.encodeURI = encodeURI;
this.encodeURIComponent = encodeURIComponent;
this.eval = eval;
this.escape = typeof escape === 'undefined' ? undefined : escape;
this.global = typeof global === 'undefined' ? undefined : global;
this.isFinite = isFinite;
this.isNaN = isNaN;
this.parseFloat = parseFloat;
this.parseInt = parseInt;
this.root = typeof root === 'undefined' ? undefined : root;
this.undefined = undefined;
this.unescape = typeof unescape === 'undefined' ? undefined : unescape;
this.AbortController = typeof AbortController === 'undefined' ? undefined : AbortController;
this.AbortSignal = typeof AbortSignal === 'undefined' ? undefined : AbortSignal;
this.Array = Array;
this.Object = Object;
this.Function = Function;
`);
