import HTMLElement from '../nodes/html-element/HTMLElement';
import HTMLTemplateElement from '../nodes/html-template-element/HTMLTemplateElement';
import HTMLFormElement from '../nodes/html-form-element/HTMLFormElement';
import HTMLInputElement from '../nodes/html-input-element/HTMLInputElement';
import HTMLTextAreaElement from '../nodes/html-text-area-element/HTMLTextAreaElement';
import SVGSVGElement from '../nodes/svg-element/SVGSVGElement';
import SVGElement from '../nodes/svg-element/SVGElement';
import HTMLScriptElement from '../nodes/html-script-element/HTMLScriptElement';
import HTMLImageElement from '../nodes/html-image-element/HTMLImageElement';
import HTMLLinkElement from '../nodes/html-link-element/HTMLLinkElement';
import HTMLStyleElement from '../nodes/html-style-element/HTMLStyleElement';
import HTMLLabelElement from '../nodes/html-label-element/HTMLLabelElement';
import HTMLSlotElement from '../nodes/html-slot-element/HTMLSlotElement';
import HTMLMetaElement from '../nodes/html-meta-element/HTMLMetaElement';
import HTMLBaseElement from '../nodes/html-base-element/HTMLBaseElement';
import HTMLSelectElement from '../nodes/html-select-element/HTMLSelectElement';
import HTMLOptionElement from '../nodes/html-option-element/HTMLOptionElement';
import HTMLOptGroupElement from '../nodes/html-opt-group-element/HTMLOptGroupElement';
import HTMLDialogElement from '../nodes/html-dialog-element/HTMLDialogElement';

export default {
	A: HTMLElement,
	ABBR: HTMLElement,
	ADDRESS: HTMLElement,
	AREA: HTMLElement,
	ARTICLE: HTMLElement,
	ASIDE: HTMLElement,
	AUDIO: HTMLElement,
	B: HTMLElement,
	BASE: HTMLBaseElement,
	BDI: HTMLElement,
	BDO: HTMLElement,
	BLOCKQUAOTE: HTMLElement,
	BODY: HTMLElement,
	TEMPLATE: HTMLTemplateElement,
	FORM: HTMLFormElement,
	INPUT: HTMLInputElement,
	TEXTAREA: HTMLTextAreaElement,
	SCRIPT: HTMLScriptElement,
	IMG: HTMLImageElement,
	LINK: HTMLLinkElement,
	STYLE: HTMLStyleElement,
	LABEL: HTMLLabelElement,
	SLOT: HTMLSlotElement,
	SVG: SVGSVGElement,
	CIRCLE: SVGElement,
	ELLIPSE: SVGElement,
	LINE: SVGElement,
	PATH: SVGElement,
	POLYGON: SVGElement,
	POLYLINE: SVGElement,
	RECT: SVGElement,
	STOP: SVGElement,
	USE: SVGElement,
	META: HTMLMetaElement,
	BLOCKQUOTE: HTMLElement,
	BR: HTMLElement,
	BUTTON: HTMLElement,
	CANVAS: HTMLElement,
	CAPTION: HTMLElement,
	CITE: HTMLElement,
	CODE: HTMLElement,
	COL: HTMLElement,
	COLGROUP: HTMLElement,
	DATA: HTMLElement,
	DATALIST: HTMLElement,
	DD: HTMLElement,
	DEL: HTMLElement,
	DETAILS: HTMLElement,
	DFN: HTMLElement,
	DIALOG: HTMLDialogElement,
	DIV: HTMLElement,
	DL: HTMLElement,
	DT: HTMLElement,
	EM: HTMLElement,
	EMBED: HTMLElement,
	FIELDSET: HTMLElement,
	FIGCAPTION: HTMLElement,
	FIGURE: HTMLElement,
	FOOTER: HTMLElement,
	H1: HTMLElement,
	H2: HTMLElement,
	H3: HTMLElement,
	H4: HTMLElement,
	H5: HTMLElement,
	H6: HTMLElement,
	HEAD: HTMLElement,
	HEADER: HTMLElement,
	HGROUP: HTMLElement,
	HR: HTMLElement,
	HTML: HTMLElement,
	I: HTMLElement,
	IFRAME: HTMLElement,
	INS: HTMLElement,
	KBD: HTMLElement,
	LEGEND: HTMLElement,
	LI: HTMLElement,
	MAIN: HTMLElement,
	MAP: HTMLElement,
	MARK: HTMLElement,
	MATH: HTMLElement,
	MENU: HTMLElement,
	MENUITEM: HTMLElement,
	METER: HTMLElement,
	NAV: HTMLElement,
	NOSCRIPT: HTMLElement,
	OBJECT: HTMLElement,
	OL: HTMLElement,
	OPTGROUP: HTMLOptGroupElement,
	OPTION: HTMLOptionElement,
	OUTPUT: HTMLElement,
	P: HTMLElement,
	PARAM: HTMLElement,
	PICTURE: HTMLElement,
	PRE: HTMLElement,
	PROGRESS: HTMLElement,
	Q: HTMLElement,
	RB: HTMLElement,
	RP: HTMLElement,
	RT: HTMLElement,
	RTC: HTMLElement,
	RUBY: HTMLElement,
	S: HTMLElement,
	SAMP: HTMLElement,
	SECTION: HTMLElement,
	SELECT: HTMLSelectElement,
	SMALL: HTMLElement,
	SOURCE: HTMLElement,
	SPAN: HTMLElement,
	STRONG: HTMLElement,
	SUB: HTMLElement,
	SUMMARY: HTMLElement,
	SUP: HTMLElement,
	TABLE: HTMLElement,
	TBODY: HTMLElement,
	TD: HTMLElement,
	TFOOT: HTMLElement,
	TH: HTMLElement,
	THEAD: HTMLElement,
	TIME: HTMLElement,
	TITLE: HTMLElement,
	TR: HTMLElement,
	TRACK: HTMLElement,
	U: HTMLElement,
	UL: HTMLElement,
	VAR: HTMLElement,
	VIDEO: HTMLElement,
	WBR: HTMLElement
};
