/**
 * SVG attribute config.
 *
 * @see https://html.spec.whatwg.org/multipage/parsing.html#adjust-svg-attributes
 */
export default <{ [key: string]: string }>{
	attributename: 'attributeName',
	attributetype: 'attributeType',
	basefrequency: 'baseFrequency',
	baseprofile: 'baseProfile',
	calcmode: 'calcMode',
	clippathunits: 'clipPathUnits',
	diffuseconstant: 'diffuseConstant',
	edgemode: 'edgeMode',
	filterunits: 'filterUnits',
	glyphref: 'glyphRef',
	gradienttransform: 'gradientTransform',
	gradientunits: 'gradientUnits',
	kernelmatrix: 'kernelMatrix',
	kernelunitlength: 'kernelUnitLength',
	keypoints: 'keyPoints',
	keysplines: 'keySplines',
	keytimes: 'keyTimes',
	lengthadjust: 'lengthAdjust',
	limitingconeangle: 'limitingConeAngle',
	markerheight: 'markerHeight',
	markerunits: 'markerUnits',
	markerwidth: 'markerWidth',
	maskcontentunits: 'maskContentUnits',
	maskunits: 'maskUnits',
	numoctaves: 'numOctaves',
	pathlength: 'pathLength',
	patterncontentunits: 'patternContentUnits',
	patterntransform: 'patternTransform',
	patternunits: 'patternUnits',
	pointsatx: 'pointsAtX',
	pointsaty: 'pointsAtY',
	pointsatz: 'pointsAtZ',
	preservealpha: 'preserveAlpha',
	preserveaspectratio: 'preserveAspectRatio',
	primitiveunits: 'primitiveUnits',
	refx: 'refX',
	refy: 'refY',
	repeatcount: 'repeatCount',
	repeatdur: 'repeatDur',
	requiredextensions: 'requiredExtensions',
	requiredfeatures: 'requiredFeatures',
	specularconstant: 'specularConstant',
	specularexponent: 'specularExponent',
	spreadmethod: 'spreadMethod',
	startoffset: 'startOffset',
	stddeviation: 'stdDeviation',
	stitchtiles: 'stitchTiles',
	surfacescale: 'surfaceScale',
	systemlanguage: 'systemLanguage',
	tablevalues: 'tableValues',
	targetx: 'targetX',
	targety: 'targetY',
	textlength: 'textLength',
	viewbox: 'viewBox',
	viewtarget: 'viewTarget',
	xchannelselector: 'xChannelSelector',
	ychannelselector: 'yChannelSelector',
	zoomandpan: 'zoomAndPan'
};
