export default <{ [key: string]: { localName: string; className: string } }>{
	svg: { localName: 'svg', className: 'SVGSVGElement' },
	animate: { localName: 'animate', className: 'SVGAnimateElement' },
	animatemotion: { localName: 'animateMotion', className: 'SVGAnimateMotionElement' },
	animatetransform: { localName: 'animateTransform', className: 'SVGAnimateTransformElement' },
	circle: { localName: 'circle', className: 'SVGCircleElement' },
	clippath: { localName: 'clipPath', className: 'SVGClipPathElement' },
	defs: { localName: 'defs', className: 'SVGDefsElement' },
	desc: { localName: 'desc', className: 'SVGDescElement' },
	ellipse: { localName: 'ellipse', className: 'SVGEllipseElement' },
	feblend: { localName: 'feBlend', className: 'SVGFEBlendElement' },
	fecolormatrix: { localName: 'feColorMatrix', className: 'SVGFEColorMatrixElement' },
	fecomponenttransfer: {
		localName: 'feComponentTransfer',
		className: 'SVGFEComponentTransferElement'
	},
	fecomposite: { localName: 'feComposite', className: 'SVGFECompositeElement' },
	feconvolvematrix: { localName: 'feConvolveMatrix', className: 'SVGFEConvolveMatrixElement' },
	fediffuselighting: { localName: 'feDiffuseLighting', className: 'SVGFEDiffuseLightingElement' },
	fedisplacementmap: { localName: 'feDisplacementMap', className: 'SVGFEDisplacementMapElement' },
	fedistantlight: { localName: 'feDistantLight', className: 'SVGFEDistantLightElement' },
	fedropshadow: { localName: 'feDropShadow', className: 'SVGFEDropShadowElement' },
	feflood: { localName: 'feFlood', className: 'SVGFEFloodElement' },
	fefunca: { localName: 'feFuncA', className: 'SVGFEFuncAElement' },
	fefuncb: { localName: 'feFuncB', className: 'SVGFEFuncBElement' },
	fefuncg: { localName: 'feFuncG', className: 'SVGFEFuncGElement' },
	fefuncr: { localName: 'feFuncR', className: 'SVGFEFuncRElement' },
	fegaussianblur: { localName: 'feGaussianBlur', className: 'SVGFEGaussianBlurElement' },
	feimage: { localName: 'feImage', className: 'SVGFEImageElement' },
	femerge: { localName: 'feMerge', className: 'SVGFEMergeElement' },
	femergenode: { localName: 'feMergeNode', className: 'SVGFEMergeNodeElement' },
	femorphology: { localName: 'feMorphology', className: 'SVGFEMorphologyElement' },
	feoffset: { localName: 'feOffset', className: 'SVGFEOffsetElement' },
	fepointlight: { localName: 'fePointLight', className: 'SVGFEPointLightElement' },
	fespecularlighting: {
		localName: 'feSpecularLighting',
		className: 'SVGFESpecularLightingElement'
	},
	fespotlight: { localName: 'feSpotLight', className: 'SVGFESpotLightElement' },
	fetile: { localName: 'feTile', className: 'SVGFETileElement' },
	feturbulence: { localName: 'feTurbulence', className: 'SVGFETurbulenceElement' },
	filter: { localName: 'filter', className: 'SVGFilterElement' },
	foreignobject: { localName: 'foreignObject', className: 'SVGForeignObjectElement' },
	g: { localName: 'g', className: 'SVGGElement' },
	image: { localName: 'image', className: 'SVGImageElement' },
	line: { localName: 'line', className: 'SVGLineElement' },
	lineargradient: { localName: 'linearGradient', className: 'SVGLinearGradientElement' },
	marker: { localName: 'marker', className: 'SVGMarkerElement' },
	mask: { localName: 'mask', className: 'SVGMaskElement' },
	metadata: { localName: 'metadata', className: 'SVGMetadataElement' },
	mpath: { localName: 'mpath', className: 'SVGMPathElement' },
	path: { localName: 'path', className: 'SVGPathElement' },
	pattern: { localName: 'pattern', className: 'SVGPatternElement' },
	polygon: { localName: 'polygon', className: 'SVGPolygonElement' },
	polyline: { localName: 'polyline', className: 'SVGPolylineElement' },
	radialgradient: { localName: 'radialGradient', className: 'SVGRadialGradientElement' },
	rect: { localName: 'rect', className: 'SVGRectElement' },
	script: { localName: 'script', className: 'SVGScriptElement' },
	set: { localName: 'set', className: 'SVGSetElement' },
	stop: { localName: 'stop', className: 'SVGStopElement' },
	style: { localName: 'style', className: 'SVGStyleElement' },
	switch: { localName: 'switch', className: 'SVGSwitchElement' },
	symbol: { localName: 'symbol', className: 'SVGSymbolElement' },
	text: { localName: 'text', className: 'SVGTextElement' },
	textpath: { localName: 'textPath', className: 'SVGTextPathElement' },
	title: { localName: 'title', className: 'SVGTitleElement' },
	tspan: { localName: 'tspan', className: 'SVGTSpanElement' },
	use: { localName: 'use', className: 'SVGUseElement' },
	view: { localName: 'view', className: 'SVGViewElement' }
};
