name: Commit
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./packages/*/npm-shrinkwrap.json') }}-${{ hashFiles('./npm-shrinkwrap.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm ci --ignore-scripts
      - run: npm run bootstrap-ci
      - run: npm run validate-commit-messages
      - run: npm run compile
      - run: npm run lint
      - run: npm run test